Evaluacion/virtual/prueba/apps/gestion_estudiante/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='estudiantes'),
    path('crearEstudiantes', views.crearEstudiante, name='crear_estudiantes'),

    path('materias/<int:cedula>/', views.listarMaterias, name="materias"),
    path('crearMaterias/<int:cedula>/', views.crearMaterias, name='crear_materias'),
]

Evaluacion/virtual/prueba/prueba/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('estudiantes/', include('apps.gestion_estudiantes.urls')),
    
]

Evaluacion/virtual/prueba/apps/gestion_estudiante/models.py
from django.db import models

# Create your models here.

Evaluacion/virtual/prueba/apps/modelo/models.py
from django.db import models

# Create your models here.
class Estudiante(models.Model):

    listaGenero = (
        ('femenino','Femenino'),
        ('masculino', 'Masculino')
    )
    estudiannte_id = models.AutoField(primary_key = True)
    cedula = models.CharField(max_length = 10, unique = True, null = False)
    nombres = models.CharField(max_length = 70, null = False)
    apellidos = models.CharField(max_length = 70, null = False)
    genero = models.CharField(max_length = 30, choices = listaGenero, default = 'femenino')
    date_created = models.DateTimeField(auto_now_add = True)
    def __str__ (self):
        return self.cedula

class Materia(models.Model):

    materia_id = models.AutoField(primary_key = True)
    nombre = models.CharField(max_length = 70, null = False)
    nota1 = models.DecimalField(max_digits = 10, decimal_places = 2, null = False)
    nota2 = models.DecimalField(max_digits = 10, decimal_places = 2, null = False)
    nota3 = models.DecimalField(max_digits = 10, decimal_places = 2, null = False)
    promedio = models.DecimalField(max_digits = 10, decimal_places = 2, null = False)
    date_created = models.DateTimeField(auto_now_add = True)

Evaluacion/virtual/prueba/apps/gestion_estudiante/forms.py
from django import forms
from apps.modelo.models import Estudiante, Materia

class FormularioEstudiante(forms.ModelForm):
    class Meta:
        model = Estudiante
        fields = ["cedula","nombres","genero","apellidos"]

class FormularioMateria(forms.ModelForm):
    class Meta:
        model = Materia
        fields = ["nombre","nota1","nota2","nota3","promedio"]

Evaluacion/virtual/prueba/apps/gestion_estudiante/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render
from apps.modelo.models import Estudiante, Materia
from .forms import FormularioEstudiante, FormularioMateria
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group, User   


def index(request):
    usuario = request.user
    if usuario.groups.filter(name = "gestion_estudiantes").exists():
        listaEstudiantes = Estudiante.objects.all() 
        #manejo del ORM 
        
        return render (request, 'estudiantes/index.html', locals())

def crearEstudiante(request):
    formulario_estudiante = FormularioEstudiante(request.POST)
    formulario_materia = FormularioMateria(request.POST)
    if request.method == 'POST':
        if formulario_estudiante.is_valid() 

            estudiante = Estudiante()
            datos_estudiante = formulario_estudiante.cleaned_data
            estudiante.cedula = datos_estudiante.get('cedula')
            estudiante.nombres = datos_estudiante.get('nombres')
            estudiante.apellidos = datos_estudiante.get('apellidos')
            #ORM
            
            Estudiante.save()

        return redirect(index)
    return render (request, 'estudiantes/crear.html', locals())



def listarMaterias(request, cedula):
    estudiante = Estudiante.objects.get(cedula=cedula)
    materia = Materia.objects.filter(estudiante=estudiante)
    return render(request, 'materias/index.html', locals())

def crearMaterias(request):
    formulario_materia = FormularioMateria(request.POST)
    estudiante = Estudiante.objects.get(cedula=cedula)
    if request.method == 'POST':
        if formulario_materia.is_valid():
            materia = Materia()
            datos_materia = formulario_materia.cleaned_data
            materia.nombre = datos_materia.get('nombre')
            materia.nota1 = datos_materia.get('nota1')
            materia.nota2 = datos_materia.get('nota2')
            materia.nota3 = datos_materia.get('nota3')
            materia.promedio = datos_materia.get('promedio')
            
            materia.estudiante = estudiante
            #ORM
            materia.save()
        return redirect(index)
    return render (request, 'materias/crear.html', locals())

Evaluacion/virtual/prueba/apps/modelo/views.py
from django.shortcuts import render

# Create your views here.

Evaluacion/virtual/prueba/templates/estudiantes/crear.html
{% extends 'master.html' %}
{% block contenido %}

<html>

<head>
    <meta>
    <title>Crear Estudiante</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>
<h4>Crear Estudiante</h4>
<div class="container">
    <form method="POST">{% csrf_token %}
        <div class="form-group">
            <label for="id_cedula">Cedula:</label>
            <input type="text" class="form-control" name="cedula" maxlength="10" required id="id_cedula">
        </div><br>
        <div class="form-group">
            <label for="id_apellidos">Apellidos:</label>
            <input type="text" class="form-control" name="apellidos" maxlength="70" required id="id_apellidos">
        </div><br>
        <div class="form-group">
            <label for="id_nombres">Nombres:</label>
            <input type="text" class="form-control" name="nombres" maxlength="70" required id="id_nombres">
        </div><br>
        <div class="form-group">
            <label for="id_genero">Genero:</label>
            <select name="genero" class="form-control" id="id_genero">
                <option value="femenino">Femenino</option>

                <option value="masculino">Masculino</option>
            </select>
        </div><br>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">Crear Estudiante</button>
        </div><br>
    </form>
</div>

</html>
{% endblock %}

Evaluacion/virtual/prueba/templates/estudiantes/index.html
{% extends 'master.html' %}
{% block contenido %}

<html>

<head>
    <meta>
    <title>Estudiantes</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <h4>Lista de Estudiantes</h4>
            <form class="d-flex" method="POST">{% csrf_token %}
                <a style="margin-left: 10px" class="btn btn-primary" href="{% url 'crear_estudiantes'%}" role="button">Nuevo Cliente</a>
            </form>
        </div>
    </nav>

    <div class="container">
        <table class="table table-striped table-bordered">
            <thead>
                <tr class="table-dark">
                    <th scope="col">Cedula</th>
                    <th scope="col">Apellido</th>
                    <th scope="col">Nombres</th>
                </tr>
            </thead>
            <tbody>
                {% for estudiante in listaEstudiantes %}
                <tr>
                    <td class="table-success">{{estudiante.cedula}}</td>
                    <td class="table-info">{{estudiante.apellidos}}</td>
                    <td class="table-primary">{{estudiante.nombres}}</td>
                </tr>

                {% endfor %}
            </tbody>
        </table>
    </div>
</body>

</html>
{% endblock %}

Evaluacion/virtual/prueba/templates/footer.html
<div class="card-footer text-white bg-secondary">
    <footer>
        <p><span style='font-size:20px;'>&#128102;</span> Autor: Jaime Paqui</p>
        <p><span style='font-size:20px;'>&#9742;</span> Telefono: 0986542760</p>
        <p><span style='font-size:20px;'>&#64;</span> Correo Electronico:jaime.paqui@unl.edu.ec</p>
        <p><span style='font-size:20px;'>&#127960;</span> Direccion:Guadalupe.</p>
    </footer>

</div>

Evaluacion/virtual/prueba/templates/master.html
<html>

<head>
    <meta>
    <title>Cooperativa 2021</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/dce97ec0a3.js" crossorigin="anonymous"></script>
</head>

<body>

    {% block contenido %}
    {% endblock%}

    {% include "footer.html" %}
</body>

</html>

Evaluacion/virtual/prueba/templates/materias/crear.html
{% extends 'master.html' %}
{% block contenido %}

<html>

<head>
    <meta>
    <title>Crear Materias</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>
<h4>Crear Materias</h4>
<div class="container">
    <form method="POST">{% csrf_token %} 
        <div class="form-group">
            <label for="id_nombres">Nombre:</label>
            <input type="text" class="form-control" name="nombre" maxlength="70" required id="id_nombre">
        </div><br>
        <div class="form-group">
            <label for="id_saldo">nota 1:</label> 
            <input type="number" class="form-control" name="nota1" step="0.01" required id="id_nota1">
        </div><br>
        <div class="form-group">
            <label for="id_saldo">nota2:</label> 
            <input type="number" class="form-control" name="nota2" step="0.01" required id="id_nota2">
        </div><br>
        <div class="form-group">
            <label for="id_saldo">nota3:</label> 
            <input type="number" class="form-control" name="nota3" step="0.01" required id="id_nota3">
        </div><br>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">Crear Materia</button>
        </div><br>
    </form>
</div>

</html>
{% endblock %}

Evaluacion/virtual/prueba/templates/materias/index.html
{% extends 'master.html' %}
{% block contenido %}


<h4>Lista de materias del estudiante:</h4>
<p>
    Nombre: {{estudiante.nombres}}<br>
    Apellido: {{estudiante.apellidos}}
</p>


<div class="container">
    <a class="btn btn-primary" role="button" href="{% url 'crear_materias' estudiante.cedula %}">Nueva Materia</a>
    <table class="table table-striped table-bordered">
        <thead>
            <tr class="table-dark">
                <th>Nombre</th>
                <th>Nota1</th>
                <th>Nota2</th>
                <th>Nota3</th>
                <th>Promedio</th>
            </tr>
        </thead>
        <tbody>
            {% for materia in Materias}
                <tr>
                    <th scope="col">{{materia.nummbre}}</th>
                    <th scope="col">{{materia.nota1}}</th>
                    <th scope="col">{{materia.nota2}}</th>
                    <th scope="col">{{materia.nota3}}</th>
                    <th scope="col">{{materia.promedio}}</th>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}